language: node_js
node_js:
  - 0.10
  - 4
  - 6
  - 7
install:
  - npm install .
  - npm install qassert
  - npm install -g qnit
  - npm install promises-aplus-tests
after_success:
  - npm install -g nyc
  - npm install -g codecov
  - nyc --reporter lcov qnit test/test-q-then.js && codecov
