language: node_js
node_js:
  - 0.10
  - 4
  - 6
  - 8
  - 10
  - 11
install:
  - npm install .
  - npm install qassert
  - npm install -g qnit
  - npm install promises-aplus-tests
after_success:
  - if [ `node -p 'process.version.slice(0, 3)'` != "v8." ]; then exit; fi
  - npm install -g nyc codecov coveralls
  - npm run coverage && codecov
  - nyc report text-lcov | coveralls
